name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/

    - name: Authenticate ngrok
      run: |
        ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo service ssh start

    - name: Set password for SSH
      run: |
       echo -e "P@ssw0rd!\nP@ssw0rd!" | sudo passwd username

    - name: Start ngrok tunnel
      run: |
        nohup ngrok tcp 22 & disown
